### ISSUE TITLE
"ValidationException" : 'One or more parameter values were invalid: Condition parameter type does not match schema type'

### ISSUE THREAD

**Issue by hcurnor** [baseprime/dynamodb#25]
Added dependencies:
```AWS = require('aws-sdk'),
    credentials = new AWS.SharedIniFileCredentials({profile: 'default'});
  const dynamo = require('dynamodb');
  dynamo.AWS.config.credentials = credentials;
  dynamo.AWS.config.update({region: "eu-central-1"});
  dynamoModels = require('../models/index')(dynamo, Joi);```

Schema I have defined:
```let Photo = dynamo.define('Photo', {
    //partitionKey || primaryKey
    hashKey: 'id',
    timestamps: true,
    schema: {
      id: dynamo.types.uuid(),
      albumId: Joi.string(),
      userId: Joi.string(),
      url: Joi.string(),
      secure_url: Joi.string(),
      original_filename: Joi.string(),
      public_id: Joi.string(),
      sizeInBytes: Joi.string(),
      format: Joi.string(),
      version: Joi.string(),
      isDeleted: Joi.boolean().default(false),
      height: Joi.number(),
      width: Joi.number(),
      previewImageUrl: Joi.string(),
      thumbnailImageUrl: Joi.string(),
      type: Joi.string(),
      resource_type: Joi.string()
    },
    //for secondary partition and sort key
    indexes: [
      {
        hashKey: 'userId', rangeKey: 'id', name: 'UserIdIndex', type: 'global'
      },
      {
        hashKey: 'albumId', rangeKey: 'createdAt', name: 'AlbumIdIndex', type: 'global'
      }
    ]
  });```

I am queering this: 
```let params = {
        Limit: parseInt(req.inputs.limit),
        IndexName: 'UserIdIndex',
        ScanIndexForward: false,
        KeyConditionExpression: "#userId = :user_Id",
        ExpressionAttributeNames: { '#userId': 'userId' },
        ExpressionAttributeValues: {
          ":user_Id": req.inputs.userId
        }
      };
      dynamoModels.Photo.query(params).exec(function (err, data) {
          if (err) {
            console.log(err);
            return errorHandler.sendError(res, err);
          }
          else
            return helper.sendResponse(res, messages.SUCCESSFUL, data);
        }
      );```

I tried this: 
```ExpressionAttributeValues: {
          ":user_Id": {
            S : req.inputs.userId 
            }
 }```
and that too
```ExpressionAttributeValues: {
          ":user_Id": {
            'S' : req.inputs.userId 
            }
 }```
but always getting an error:
`{ ValidationException: One or more parameter values were invalid: Condition parameter type does not match schema type
    at Request.extractError (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\protocol\json.js:43:27)
    at Request.callListeners (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\request.js:596:14)
    at Request.transition (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\request.js:21:10)
    at AcceptorStateMachine.runTo (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\request.js:37:9)
    at Request.<anonymous> (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\request.js:598:12)
    at Request.callListeners (E:\OneDrive\Projects\Amor\amor-server\node_modules\dynamodb\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
  message: 'One or more parameter values were invalid: Condition parameter type does not match schema type',
  code: 'ValidationException',
  time: 2018-02-12T17:08:37.455Z,
  requestId: '9HIQ5R5TG9K9THQ3EQ65C4R0HNVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 0 }`

**Comment by captainheart** [comment]
Hi @hcurnor  How did you resolve this?

**Comment by hcurnor** [comment]
Hi @captainheart Yes actually I used documentClient provided by dynamodb package with the almost same query,

const dynamo = require('dynamodb');

let params = {
        TableName: 'photos',
        IndexName: 'UserIdIndex',
        KeyConditionExpression: '#userId = :user_Id',
        FilterExpression: '#isDeleted = :is_Deleted and #isPrivate = :isPrivate',
        ExpressionAttributeNames: {'#userId': 'userId', '#isDeleted': 'isDeleted', '#isPrivate': 'isPrivate'},
        ExpressionAttributeValues: {
          ':user_Id': req.inputs.userId,
          ':is_Deleted': false,
          ':isPrivate': false
        }
      };
      var docClient = dynamo.documentClient();
      docClient.query(params, function (err, data) {
          if (err) {
            console.log(err);
            return errorHandler.sendError(res, err);
          }
          else
            return helper.sendResponse(res, messages.SUCCESSFUL, data.Items);
        }
      );
